### ISSUE TITLE
Criar frond-end do formulário para inserção de dados e documentos (ver comentários)

### ISSUE THREAD

**Issue by vimassaru** [marialigiaunifesp/prototipo_radar_urbanistico_FE#1]
Me ocorreu aqui que **de repente o analista não terá os arquivos dos documentos para inserir, mas ele leu as informações em algum processo administrativo, que cita esses dados**. Uma opção que pensei agora é do **usuário selecionar os dados que ele quer inserir, sem necessariamente haver vinculação com um documento (documento não seria um limitante do campo)**. 
**Seria como ter um formulário com 4 campos: tipo de dado, dado, fonte e referência**. Ou seja, o formulário seria mais simples e teria os seguintes campos (exemplo):

1. **Tipo de dado** (lista suspensa): número de matrícula, nome do empreendimento, nome do loteador, nome do proprietário, nome do comprador, processo judicial, auto de infração ambiental, contrato de compra e venda, número de lotes, etc.
2. **Dado**: qualquer dado de texto que o usuário poderia inserir, relacionado ao tipo de dado do item 1: nome de proprietário, número de matrícula, número do INCRA, código do imóvel, nome do loteador, processo judicial, ou seja, o dado em si.
3.  **Fonte**: apareceriam opções para o usuário selecionar de onde ele tirou o dado. Seria uma lista suspensa. Por exemplo, o usuário viu num processo judicial o número da matrícula. Ele pode inserir o número da matrícula no dado, o tipo de dado será o número de matrícula e a fonte será o processo judicial.
4. **Referência**: Número do documento ou site de onde veio a informação. Ex: número do processo judicial onde o usuário pegou o dado de número de matrícula, no exemplo anterior.

**Comment by vimassaru** [comment]
### Lista de Tarefas
- [x] Configurar o framework base
- [ ] Criar HTML Base
- [ ] Criar view do formulário
- [ ] Criar model para os dados

**Comment by marialigiaunifesp** [comment]
Combinado que a Beatriz consegue concluir o formulário na próxima semana, mas não conseguirá fazer a tela de login (outra issue).

**Comment by marialigiaunifesp** [comment]
Só falta colocar o botão CANCELAR e fazer o botão FINALIZAR salvar as alterações no banco de dados e voltar para a tela inicial.
